modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MPL2.0"
issueTrackerURL="https://gitlab.com/cable-mc/cobblemon-Cobblemon/-/issues"

[[mods]] #mandatory
modId="cobblemon" #mandatory
version="${version}" #mandatory
displayName="Cobblemon" #mandatory
#logoFile="examplemod.png" #optional
credits="Thanks to Mojang, Blockbench, Smogon, Sam Cao, and the many community contributors"
authors="The Cobblemon Team"
description='''
 This is a Pok√©mon mod
'''

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.cobblemon]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"

[[dependencies.cobblemon]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40,)" #mandatory
