before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - deploy

#TODO add client reference test process, search for import com.cablemc.pokemod.common.client

build-job:
  stage: build
  script:
      - export GRADLE_OPTS="-Xmx3G -Xms3G"
      - chmod +x ./gradlew
      - ./gradlew build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - forge/build/libs
      - fabric/build/libs

# Separate step to deploy the artifacts, save Norry the headache of keeping even more shit around
deploy-job:
  stage: deploy
#  when: manual
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - forge/build/libs/*.jar
      - fabric/build/libs/*.jar
  script: 
    - echo "Collecting artifacts..."
    - mv forge/build/libs/*-remap.jar ./
    - mv fabric/build/libs/*-remap.jar ./
    - for f in *.jar; do mv "$f" "$(echo "$f" | sed s/+/b$CI_PIPELINE_IID+/ | sed s/-remap//)"; done
  artifacts:
    expire_in: 28 days
    paths:
      - ./*.jar
#      - forge/build/libs/*-forge.jar
#      - fabric/build/libs/*-remap.jar
