before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - deploy

#TODO add client reference test process, delete client from sources and see if compilation is successful

build-job:
  stage: build
  script:
      - export GRADLE_OPTS="-Xmx3G -Xms3G"
      - chmod +x ./gradlew
      - ./gradlew build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - forge/build/libs
      - fabric/build/libs

# Separate step to deploy the artifacts, save Norry the headache of keeping even more shit around
deploy-job:
  stage: deploy
  when: manual
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - forge/build/libs/*.jar
      - fabric/build/libs/*.jar
  script: 
    - echo "Collecting artifacts..."
    - mkdir artifacts
    - mv forge/build/libs/*-forge.jar artifacts
    - mv fabric/build/libs/*-remap.jar artifacts
    - for f in artifacts/*-remap.jar; do mv "$f" "$(echo "$f" | sed s/remap/fabric/)"; done
  #    - mv forge/build/libs/*.jar ./
  artifacts:
    expire_in: 10 days  
    paths:
      - artifacts/*.jar
#      - forge/build/libs/*-forge.jar
#      - fabric/build/libs/*-remap.jar
