modLoader="kotlinforforge" #mandatory
loaderVersion="[5.3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MPL2.0"
issueTrackerURL="https://gitlab.com/cable-mc/cobblemon/-/issues"

[[mods]] #mandatory
modId="cobblemon" #mandatory
version="${version}" #mandatory
displayName="Cobblemon" #mandatory
displayURL="https://cobblemon.com/"
#logoFile="examplemod.png" #optional
credits="Thanks to Mojang, Blockbench, Smogon, and the many community contributors"
authors="The Cobblemon Team"
description='''
 Adds Pok√©mon to the world, letting you find, battle, capture, and evolve them.
'''

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
[[mixins]]
config = "mixins.cobblemon-neoforge.json"
[[mixins]]
config = "mixins.cobblemon-common.json"

[[dependencies.cobblemon]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"

[[dependencies.cobblemon]]
modId="neoforge" #mandatory
mandatory=true #mandatory
versionRange="[20.6,)" #mandatory